services:
  postgres:
    image: postgres:latest  # по умолчанию новая версия
    container_name: ${CONT_NAME_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:  # точки монтирования
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - backend
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: ${CONT_NAME_ZOOKEEPER}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend

  kafka:  # chmod +x run-init-kafka-topics.sh  пришлось раздать права, так как не выполнялся скрипт ./deployment/kafka/run-init-kafka-topics.sh
    image: docker.io/bitnami/kafka:3.3
    container_name: ${CONT_NAME_KAFKA}
    hostname: kafka
    volumes:
      - "./kafka/run-init-kafka-topics.sh:/docker-entrypoint-initdb.d/run-init-kafka-topics.sh:ro"  # read only
      - "./kafka/init-kafka-topics.sh:/init-kafka-topics.sh:ro"  # read only
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - backend
    ports:
      - 9092:9092
      - 9094:9094
  
  kafka_ui:
    image: docker.io/provectuslabs/kafka-ui:latest
    container_name: ${CONT_NAME_KAFKA_UI}
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - backend
networks:
  backend: